### ISSUE TITLE
Model training issue, if there is possible to do parallel computing for the model training step?

### ISSUE THREAD

**Issue by yx0516** [MolecularAI/GraphINVENT#23]
Hello @rociomer, @suneelbvs @divnori @kant thank you very much for this work!

In the model training task, my dataset has 1.2 million molecules,  the preprocessing of the dataset has been done. 
At present, slurm and multi-core processing are set up, however the model training step also only use a single process??, if there is possible to do parallel computing for the model training step?

Thank you very much for your help and I look forward to your reply!
Best Regards,

**Comment by rociomer** [comment]
We have not yet implemented this as it doesn't usually take "too long" to train a model, even with 1M molecules. Depending on the size of the molecules, training can take about a day or so as a single process on a GPU. However, that is definitely something worth considering for future versions of GraphINVENT.

**Comment by yx0516** [comment]
That's fine.  Thanks a lot!
