### ISSUE TITLE
An error in generating graphs

### ISSUE THREAD

**Issue by gooaah** [MolecularAI/GraphINVENT#4]
Dear developers,

I meet a problem when I try to generate graphs after training (follow 1_introduction.md). The error is:

```
Traceback (most recent call last):
  File "./graphinvent/main.py", line 61, in <module>
    main()
  File "./graphinvent/main.py", line 47, in main
    workflow.generation_phase()
  File "/cobra/u/gaoh/generate/GraphINVENT/graphinvent/Workflow.py", line 312, in generation_phase
    self.generate_graphs(n_samples=self.constants.n_samples)
  File "/cobra/u/gaoh/generate/GraphINVENT/graphinvent/Workflow.py", line 418, in generate_graphs
    self.analyzer.evaluate_generated_graphs(generated_graphs=graphs,
AttributeError: 'NoneType' object has no attribute 'evaluate_generated_graphs'
```

**Comment by rociomer** [comment]
Thanks for pointing this out.

The Analyzer object needs to be initialized at the top of the generation_phase() method, as the Analyzer is needed later so as to call the evaluate_generated_graphs() method. This should be fixed now!

**Comment by gooaah** [comment]
Moreover, I am trying to generating crystal based on your network. Crystal can also be represented by graph but the meaning of edge features is different. So I should modify the definition of edge features in GraphINVENT. Could you give me some suggestions?

**Comment by gooaah** [comment]
Thank you!
